# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Deploy to build-staging

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build-staging:

#     runs-on: ubuntu-latest

#     steps:

#       - name: Deploy to GCP Storage Bucket
#         uses: google-github-actions/upload-cloud-storage@v0.2.0
#         with:
#           credentials:  ${{secrets.gcp_service_key}}
#           path:  ${{secrets.export_bundle_path}}
#           destination:  ${{secrets.gcp_bucket_name}}

