# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to build-staging

on:
  push:
    branches: [main, workflow-test]
  pull_request:
    branches: [main, workflow-test]

jobs:
  create-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -vp ./build/output/styles/
      - name: Copy Index
        run: cp ./index.html ./build/output/index.html
      - name: Compile CSS
        uses: gha-utilities/sass-build@v0.3.7
        with:
          source: |
            styles/default.scss
            styles/index.scss
          destination: |
            build/output/styles/default.css
            build/output/styles/index.css
      - name: Deploy to GCP Storage Bucket
        uses: google-github-actions/upload-cloud-storage@v0.2.0
        with:
          credentials: ${{secrets.gcp_service_key}}
          path: |
            ./img
            ./favicon.ico
            ./index.html
            ./build/output/styles
          destination: ${{secrets.gcp_bucket_name}}
